"""removed user constraint in Comment model 

Revision ID: 419ff0dbbaf3
Revises: 18c0f750c91a
Create Date: 2018-05-26 21:49:46.818216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '419ff0dbbaf3'
down_revision = '18c0f750c91a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
