"""added a email validation rule

Revision ID: a797ff5c4ead
Revises: 8092db6fcad2
Create Date: 2018-05-27 13:42:15.027270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a797ff5c4ead'
down_revision = '8092db6fcad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'subscription', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription', type_='unique')
    # ### end Alembic commands ###
